name: app workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: run setup
        run: make setup

      - name: start
        run: make start

      - name: run tests
        run: make test

      - name: run lint
        run: make lint
